const menu = {
    list() {
        return [
					{
						"backMenu":[
							{
							    "child":[
							        {
							            "buttons":[
							                "查看",
							                "新增",
							                "修改",
							                "删除"
							            ],
							            "menu":"专家管理",
							            "menuJump":"列表",
							            "tableName":"zhuanjia"
							        }
							    ],
							    "menu":"专家管理"
							}
							,{
							    "child":[
							        {
							            "buttons":[
							                "查看",
							                "新增",
							                "修改",
							                "删除"
							            ],
							            "menu":"编辑管理",
							            "menuJump":"列表",
							            "tableName":"bianji"
							        }
							    ],
							    "menu":"编辑管理"
							}
							,{
							    "child":[
							        {
							            "buttons":[
							                "查看",
							                "新增",
							                "修改",
							                "删除"
							            ],
							            "menu":"用户管理",
							            "menuJump":"列表",
							            "tableName":"yonghu"
							        }
							    ],
							    "menu":"用户管理"
							}
							,{
							    "child":[
							        {
							            "buttons":[
							                "查看",
							                "删除"
							            ],
							            "menu":"稿件信息管理",
							            "menuJump":"列表",
							            "tableName":"gaojian"
							        }
							    ],
							    "menu":"稿件信息管理"
							}
							,{
							    "child":[
							        {
							            "buttons":[
							                "查看",
							                "新增",
							                "修改",
							                "删除"
							            ],
							            "menu":"稿件类型管理",
							            "menuJump":"列表",
							            "tableName":"dictionaryGaojian"
							        }
							        ,
							        {
							            "buttons":[
							                "查看",
							                "新增",
							                "修改",
							                "删除"
							            ],
							            "menu":"公告类型管理",
							            "menuJump":"列表",
							            "tableName":"dictionaryNews"
							        }
							    ],
							    "menu":"基础数据管理"
							}
							,{
							    "child":[
							        {
							            "buttons":[
							                "查看",
							                "新增",
							                "修改",
							                "删除"
							            ],
							            "menu":"公告管理",
							            "menuJump":"列表",
							            "tableName":"news"
							        }
							    ],
							    "menu":"公告管理"
							}
						],
						"frontMenu":[],
						"hasBackLogin":"是",
						"hasBackRegister":"否",
						"hasFrontLogin":"否",
						"hasFrontRegister":"否",
						"roleName":"管理员",
						"tableName":"users"
					},
					{
						"backMenu":[
							{
							    "child":[
							        {
							            "buttons":[
							                "查看",
							                "审核"
							            ],
							            "menu":"稿件信息管理",
							            "menuJump":"列表",
							            "tableName":"gaojian"
							        }
							    ],
							    "menu":"稿件信息管理"
							}
							,{
							    "child":[
							        {
							            "buttons":[
							                "查看"
							            ],
							            "menu":"公告管理",
							            "menuJump":"列表",
							            "tableName":"news"
							        }
							    ],
							    "menu":"公告管理"
							}
						],
						"frontMenu":[],
						"hasBackLogin":"是",
						"hasBackRegister":"否",
						"hasFrontLogin":"否",
						"hasFrontRegister":"否",
						"roleName":"编辑",
						"tableName":"bianji"
					},
					{
						"backMenu":[
							{
							    "child":[
							        {
							            "buttons":[
							                "查看",
							                "审核"
							            ],
							            "menu":"稿件信息管理",
							            "menuJump":"列表",
							            "tableName":"gaojian"
							        }
							    ],
							    "menu":"稿件信息管理"
							}
							,{
							    "child":[
							        {
							            "buttons":[
							                "查看"
							            ],
							            "menu":"公告管理",
							            "menuJump":"列表",
							            "tableName":"news"
							        }
							    ],
							    "menu":"公告管理"
							}
						],
						"frontMenu":[],
						"hasBackLogin":"是",
						"hasBackRegister":"否",
						"hasFrontLogin":"否",
						"hasFrontRegister":"否",
						"roleName":"专家",
						"tableName":"zhuanjia"
					},
					{
						"backMenu":[
							{
							    "child":[
							        {
							            "buttons":[
							                "查看",
							                "新增",
							                "删除"
							            ],
							            "menu":"稿件信息管理",
							            "menuJump":"列表",
							            "tableName":"gaojian"
							        }
							    ],
							    "menu":"稿件信息管理"
							}
							,{
							    "child":[
							        {
							            "buttons":[
							                "查看"
							            ],
							            "menu":"公告管理",
							            "menuJump":"列表",
							            "tableName":"news"
							        }
							    ],
							    "menu":"公告管理"
							}
						],
						"frontMenu":[],
						"hasBackLogin":"是",
						"hasBackRegister":"否",
						"hasFrontLogin":"否",
						"hasFrontRegister":"否",
						"roleName":"用户",
						"tableName":"yonghu"
					},
					
				]
		}
}
export default menu;
